# Generated by Django 5.1.7 on 2025-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_minutes_before',
            field=models.IntegerField(default=15),
        ),
    ]
