# Generated by Django 5.1.7 on 2025-04-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_event_reminder_minutes_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
