# Generated by Django 5.1.7 on 2025-04-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_groupmembership_show_in_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='schedules.event'),
        ),
    ]
