# Generated by Django 5.1.7 on 2025-04-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_event_recurring_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('school', 'School'), ('fun', 'Fun'), ('gym', 'Gym'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
